volumes:
  backend_db:

  
services:
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine  # not the latest version
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro  # ro -> read only
      - ./certs:/etc/nginx/ssl:ro
    ports:
      - "443:443"
      - "80:80"

  backend:
    restart: always
    build: ./backend
    container_name: back
    image: back
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: file:/app/backend/prisma/prisma/dev.db
    volumes:
      - backend_db:/app/backend/prisma
      - ./certs:/certs:ro
    # env_file:
    #   - .env
  
  frontend:
    restart: always
    build: ./frontend
    container_name: front
    image: front
    ports:
      - "8080:8080"
    # env_file:
    #   - .env