version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence

  backend:
    container_name: back
    build: ./backend
    image: back
    restart: always
    environment:
      DATABASE_URL: file:/app/backend/prisma/prisma/dev.db
    volumes:
      - backend_db:/app/backend/prisma
      - ./certs:/certs:ro
    expose:
      - "3000"
    networks:
      - transcendence

  frontend:
    container_name: front
    build: ./frontend
    image: front
    restart: always
    expose:
      - "8080"
    networks:
      - transcendence

volumes:
  backend_db:

networks:
  transcendence:
    driver: bridge
